spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

knife4j:
  # 是否开启swagger
  enable: true

apryse:
  # license内容
  license: "改成自己的"
  # 本地组件库路径
  libPath: "改成自己的resources/lib的绝对路径"